return {
  {
    "mason-org/mason.nvim",
    opts = function(_, opts)
      opts.ensure_installed = opts.ensure_installed or {}
      vim.list_extend(opts.ensure_installed, {
        -- LSPs
        "angular-language-server",
        "ansible-language-server",
        "asm-lsp",
        "awk-language-server",
        "azure-pipelines-language-server",
        "bash-language-server",
        "clangd",
        "cmake-language-server",
        "css-lsp",
        "css-variables-language-server",
        "cssmodules-language-server",
        "cucumber-language-server",
        "deno",
        "docker-compose-language-service",
        "docker-language-server",
        "dockerfile-language-server",
        "emmet-ls",
        "eslint-lsp",
        "gh-actions-language-server",
        "gopls",
        "gradle-language-server",
        "helm-ls",
        "html-lsp",
        "htmx-lsp",
        "jdtls",
        "jq-lsp",
        "json-lsp",
        "jsonld-lsp",
        "kotlin-language-server",
        "lua-language-server",
        "marksman",
        "neocmakelsp",
        "nextls",
        "nginx-language-server",
        "pyright",
        "ruff-lsp",
        "rust-analyzer",
        "sqls",
        "svelte-language-server",
        "taplo",
        "terraform-ls",
        "texlab",
        "typescript-language-server",
        "vtsls",
        "vue-language-server",
        "yaml-language-server",
        "zls",
        
        -- Linters
        "ansible-lint",
        "checkstyle",
        "cmakelint",
        "cpplint",
        "eslint_d",
        "flake8",
        "golangci-lint",
        "hadolint",
        "htmlhint",
        "jsonlint",
        "ktlint",
        "markdownlint",
        "markdownlint-cli2",
        "ruff",
        "shellcheck",
        "sqlfluff",
        "stylelint",
        "tflint",
        "yamllint",
        
        -- Formatters
        "asmfmt",
        "black",
        "clang-format",
        "cmakelang",
        "gofumpt",
        "goimports",
        "google-java-format",
        "htmlbeautifier",
        "isort",
        "jq",
        "json-to-struct",
        "latexindent",
        "markdown-toc",
        "nginx-config-formatter",
        "prettier",
        "prettierd",
        "shfmt",
        "stylua",
        "yamlfmt",
        
        -- Debuggers (DAP)
        "bash-debug-adapter",
        "codelldb",
        "cpptools",
        "debugpy",
        "delve",
        "java-debug-adapter",
        "java-test", -- Java test runner
        "js-debug-adapter",
        "kotlin-debug-adapter",
        
        -- Tools
        "gh", -- GitHub CLI
        "gotests",
        "postgrestools",
      })
    end,
  },
}
