# ShedOS Live Environment mkinitcpio configuration

MODULES=()

BINARIES=()

FILES=()

# Archiso hooks required for live boot
HOOKS=(base udev plymouth modconf archiso archiso_loop_mnt block filesystems keyboard)

COMPRESSION="zstd"
