#!/usr/bin/env bash
# render-meta-depends.sh — regenerate packaging/shedos-meta/PKGBUILD.
#
# Source of truth:
#   packages/official/*.txt      → Arch core/extra/multilib deps
#   packages/aur.txt              → AUR deps the ISO pacstrap installs
#   packages/aur-norepublish.txt  → subset of aur.txt we are not allowed to
#                                   redistribute under the ShedOS key (EULA).
#                                   Moved from depends= to optdepends= so
#                                   `pacman -Syu shedos-meta` on an installed
#                                   system still resolves (those packages live
#                                   on AUR, not in [shedos]; shedos-welcome
#                                   handles them via yay at user consent).
#
# Output: packaging/shedos-meta/PKGBUILD with a fresh depends=() + optdepends=().
#
# Run this whenever packages/ changes, or let CI do it. The generated file
# is committed so local makepkg works without re-running the script first.

set -euo pipefail

here=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
root=$(cd -- "$here/.." && pwd)
out=$root/packaging/shedos-meta/PKGBUILD

mapfile -t official < <(
    find "$root/packages/official" -maxdepth 1 -type f -name '*.txt' -print0 \
        | xargs -0 grep -hEv '^\s*(#|$)' \
        | sort -u
)
mapfile -t aur < <(
    grep -hEv '^\s*(#|$)' "$root/packages/aur.txt" 2>/dev/null | sort -u
)

# Build an associative set of norepublish package names for O(1) lookup.
declare -A norepublish=()
if [[ -f "$root/packages/aur-norepublish.txt" ]]; then
    while read -r p; do
        [[ -z $p || $p == \#* ]] && continue
        norepublish[$p]=1
    done < <(grep -hEv '^\s*(#|$)' "$root/packages/aur-norepublish.txt")
fi

# ShedOS packages that ship from the [shedos] repo. Listed explicitly so a
# typo here fails loudly rather than silently dropping a shedos-* dep.
shedos_pkgs=(
    shedos-keyring
    shedos-system
    shedos-hyprland
    shedos-nvim
    shedos-branding
    shedos-kernel
    # shedos-kernel-headers is a split package off shedos-kernel's PKGBUILD.
    # Required as a hard dep because we ship nvidia-open-dkms (and other
    # potential DKMS modules) by default — DKMS iterates every installed
    # kernel under /usr/lib/modules/ and tries to `make` against its
    # /build/ symlink. Without these headers, `dkms install nvidia` fails
    # for the shedos-kernel with "Missing 6.19.14-zen1-1-shedos-kernel
    # kernel headers" during pacstrap or post-install.
    shedos-kernel-headers
    shedos-screensaver
)

# De-dupe across all sources. Keep shedos-* first so the order reads naturally
# in the generated PKGBUILD. Split: republishable → depends=; proprietary AUR
# → optdepends= (cannot live in [shedos], users install via yay).
declare -A seen
ordered=()
optional=()
for p in "${shedos_pkgs[@]}" "${official[@]}" "${aur[@]}"; do
    [[ -z $p ]] && continue
    [[ -n ${seen[$p]:-} ]] && continue
    seen[$p]=1
    if [[ -n ${norepublish[$p]:-} ]]; then
        optional+=("$p")
    else
        ordered+=("$p")
    fi
done

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

# Read release version from the single source of truth. CalVer (YYYY.MM.DD).
# scripts/bump-version.sh owns writing this file — we just read it.
version=$(cat "$root/VERSION")

# Preserve the current pkgrel if shedos-meta already exists and pkgver
# matches; that way re-running this script during a bump-version.sh pkgrel-
# only bump doesn't reset pkgrel to 1.
pkgrel=1
if [[ -f "$out" ]]; then
    existing_ver=$(awk -F= '/^pkgver=/ {print $2; exit}' "$out" 2>/dev/null || true)
    existing_rel=$(awk -F= '/^pkgrel=/ {print $2; exit}' "$out" 2>/dev/null || true)
    if [[ "$existing_ver" == "$version" && -n "$existing_rel" ]]; then
        pkgrel=$existing_rel
    fi
fi

{
    cat <<EOF
# Maintainer: ShedOS <https://github.com/theshedman/shedos>
#
# AUTO-GENERATED by scripts/render-meta-depends.sh — do not edit by hand.
# Edit packages/official/*.txt or packages/aur.txt, then re-run the script.
# pkgver is read from the repo-root VERSION file; bump via bump-version.sh.
#
# Zero-file metapackage. Pulls in every ShedOS package plus every Arch / AUR
# package a default ShedOS install needs. Replaces archiso/packages.x86_64
# as the source of truth for "what's on a fresh install".

pkgname=shedos-meta
pkgver=$version
pkgrel=$pkgrel
pkgdesc='ShedOS meta-package — installs the full default ShedOS environment'
arch=('any')
url='https://github.com/theshedman/shedos'
license=('GPL-3.0-or-later')
depends=(
EOF
    for p in "${ordered[@]}"; do
        printf "    '%s'\n" "$p"
    done
    cat <<'EOF'
)
optdepends=(
EOF
    for p in "${optional[@]}"; do
        printf "    '%s: proprietary AUR package; install via shedos-welcome / yay'\n" "$p"
    done
    cat <<'EOF'
)

package() {
    # Intentionally empty — this is a metapackage.
    :
}
EOF
} > "$tmp"

install -Dm644 "$tmp" "$out"

echo "Wrote $out ($(wc -l < "$tmp") lines, ${#ordered[@]} deps, ${#optional[@]} optdeps)"
