#!/usr/bin/env bash
# render-meta-depends.sh — regenerate packaging/shedos-meta/PKGBUILD.
#
# Source of truth: packages/official/*.txt + packages/aur.txt.
# Output: packaging/shedos-meta/PKGBUILD with a fresh depends=() array.
#
# Run this whenever packages/ changes, or let CI do it. The generated file
# is committed so local makepkg works without re-running the script first.

set -euo pipefail

here=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
root=$(cd -- "$here/.." && pwd)
out=$root/packaging/shedos-meta/PKGBUILD

mapfile -t official < <(
    find "$root/packages/official" -maxdepth 1 -type f -name '*.txt' -print0 \
        | xargs -0 grep -hEv '^\s*(#|$)' \
        | sort -u
)
mapfile -t aur < <(
    grep -hEv '^\s*(#|$)' "$root/packages/aur.txt" 2>/dev/null | sort -u
)

# ShedOS packages that ship from the [shedos] repo. Listed explicitly so a
# typo here fails loudly rather than silently dropping a shedos-* dep.
shedos_pkgs=(
    shedos-keyring
    shedos-system
    shedos-hyprland
    shedos-nvim
    shedos-branding
)

# De-dupe across all sources. Keep shedos-* first so the order reads naturally
# in the generated PKGBUILD.
declare -A seen
ordered=()
for p in "${shedos_pkgs[@]}" "${official[@]}" "${aur[@]}"; do
    [[ -z $p ]] && continue
    if [[ -z ${seen[$p]:-} ]]; then
        seen[$p]=1
        ordered+=("$p")
    fi
done

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

{
    cat <<'EOF'
# Maintainer: ShedOS <https://github.com/theshedman/shedos>
#
# AUTO-GENERATED by scripts/render-meta-depends.sh — do not edit by hand.
# Edit packages/official/*.txt or packages/aur.txt, then re-run the script.
#
# Zero-file metapackage. Pulls in every ShedOS package plus every Arch / AUR
# package a default ShedOS install needs. Replaces archiso/packages.x86_64
# as the source of truth for "what's on a fresh install".

pkgname=shedos-meta
pkgver=0.1.0
pkgrel=1
pkgdesc='ShedOS meta-package — installs the full default ShedOS environment'
arch=('any')
url='https://github.com/theshedman/shedos'
license=('GPL-3.0-or-later')
depends=(
EOF
    for p in "${ordered[@]}"; do
        printf "    '%s'\n" "$p"
    done
    cat <<'EOF'
)

package() {
    # Intentionally empty — this is a metapackage.
    :
}
EOF
} > "$tmp"

install -Dm644 "$tmp" "$out"

echo "Wrote $out ($(wc -l < "$tmp") lines, ${#ordered[@]} deps)"
