#!/bin/bash
# resolve-meta-closure.sh — write packages/.meta-closure.txt as the
# fully-resolved Arch transitive closure of shedos-meta's depends.
#
# Without this, render-meta-depends.sh names only the broad-list
# roots; install-time pacstrap then picks alphabetical defaults for
# any unpinned virtual provider — same trap that broke the live-ISO
# build (jack → jack2, pipewire-session-manager → pipewire-media-session).
#
# Closure input: packages/official/*.txt (broad Arch + multilib roots).
# AUR + shedos-* names are filtered from the resolution input — they
# aren't in pacman repos at script-run time — and re-applied verbatim
# by render-meta-depends.sh. Any AUR-introduced transitive Arch dep
# that isn't already in the broad closure gets pulled in by pacman at
# install time; that's a small remaining surface but keeps the script
# robust against stale files in archiso/shedos-repo/.
#
# Requires root for `pacman -Sy` (db sync). Runs in an isolated
# tempdir so the host /var/lib/pacman is untouched. Locally:
# `sudo scripts/resolve-meta-closure.sh`.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
PACKAGES_DIR="$PROJECT_ROOT/packages"
OUTPUT_FILE="$PACKAGES_DIR/.meta-closure.txt"

if [[ $EUID -ne 0 ]]; then
    echo "ERROR: must be run as root — pacman -Sy syncs the db." >&2
    echo "       Run: sudo $0" >&2
    exit 1
fi

echo "=========================================="
echo "Resolving shedos-meta Arch closure"
echo "=========================================="

declare -A aur_set
while IFS= read -r p; do
    [[ -n "$p" ]] && aur_set[$p]=1
done < <(grep -hEv '^\s*(#|$)' "$PACKAGES_DIR/aur.txt" 2>/dev/null | sort -u)

ARCH_ROOTS=()
while IFS= read -r pkg; do
    [[ -z "$pkg" || "$pkg" =~ ^# ]] && continue
    [[ "$pkg" == shedos-* ]] && continue
    [[ -n ${aur_set[$pkg]:-} ]] && continue
    ARCH_ROOTS+=("$pkg")
done < <(
    find "$PACKAGES_DIR/official" -maxdepth 1 -type f -name '*.txt' -print0 \
        | xargs -0 grep -hEv '^\s*(#|$)' \
        | sort -u
)

mapfile -t ARCH_ROOTS < <(printf '%s\n' "${ARCH_ROOTS[@]}" | sort -u)
echo "Arch roots: ${#ARCH_ROOTS[@]} packages"

TMPDIR=$(mktemp -d)
trap "rm -rf $TMPDIR" EXIT
mkdir -p "$TMPDIR/db"

cat > "$TMPDIR/pacman.conf" << 'EOF'
[options]
HoldPkg     = pacman glibc
Architecture = x86_64
SigLevel    = Never
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
EOF

echo "Syncing pacman databases into $TMPDIR/db ..."
pacman -Sy --noconfirm \
    --dbpath "$TMPDIR/db" \
    --config "$TMPDIR/pacman.conf" >/dev/null

echo "Resolving Arch transitive closure ..."
pacman -Sp --noconfirm \
    --dbpath "$TMPDIR/db" \
    --config "$TMPDIR/pacman.conf" \
    --print-format '%n' \
    "${ARCH_ROOTS[@]}" \
    | grep -vE '^shedos-' \
    | sort -u > "$TMPDIR/closure.txt"

{
    cat << 'EOF'
# AUTO-GENERATED by scripts/resolve-meta-closure.sh — do not edit.
# Full transitive closure of packages/official/*.txt resolved against
# core/extra/multilib. Consumed by scripts/render-meta-depends.sh to
# populate shedos-meta's depends=() with every Arch transitive dep
# explicit, so install-time pacstrap has no virtual-provider rolls.
# Regenerate: sudo scripts/resolve-meta-closure.sh

EOF
    cat "$TMPDIR/closure.txt"
} > "$OUTPUT_FILE"

TOTAL=$(grep -cv '^#\|^$' "$OUTPUT_FILE")
echo ""
echo "Wrote $OUTPUT_FILE ($TOTAL packages)."

if [ -n "${SUDO_USER:-}" ]; then
    chown "$SUDO_USER:$(id -gn "$SUDO_USER")" "$OUTPUT_FILE"
    echo "Restored ownership to user: $SUDO_USER"
fi

echo "=========================================="
