#!/bin/bash
# resolve-meta-closure.sh; write packages/.meta-closure.txt as the
# fully-resolved Arch transitive closure of shedos-meta's depends.
#
# Without this, render-meta-depends.sh names only the broad-list
# roots; install-time pacstrap then picks alphabetical defaults for
# any unpinned virtual provider; same trap that broke the live-ISO
# build (jack → jack2, pipewire-session-manager → pipewire-media-session).
#
# Closure input: packages/official/*.txt (broad Arch + multilib roots).
# AUR + shedos-* names are filtered from the resolution input; they
# aren't in pacman repos at script-run time; and re-applied verbatim
# by render-meta-depends.sh. Any AUR-introduced transitive Arch dep
# that isn't already in the broad closure gets pulled in by pacman at
# install time; that's a small remaining surface but keeps the script
# robust against stale files in the channel.
#
# A closure name the release manifest also names is written down with a
# marker: the channel serves that package, not Arch, and the renderer emits
# the manifest's pinned form for it instead of a bare Arch name.
#
# Requires root for `pacman -Sy` (db sync). Runs in an isolated
# tempdir so the host /var/lib/pacman is untouched. Locally:
# `sudo tools/resolve-meta-closure.sh`. In CI it is the meta workflow's
# closure job, which is where the root container already is.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=tools/lib-meta.sh
source "$SCRIPT_DIR/lib-meta.sh"
PACKAGES_DIR=$META_PACKAGES
OUTPUT_FILE=$META_CLOSURE

if [[ $EUID -ne 0 ]]; then
    echo "ERROR: must be run as root — pacman -Sy syncs the db." >&2
    echo "       Run: sudo $0" >&2
    exit 1
fi

echo "=========================================="
echo "Resolving shedos-meta Arch closure"
echo "=========================================="

declare -A aur_set
while IFS= read -r p; do
    [[ -n "$p" ]] && aur_set[$p]=1
done < <(list_names "$PACKAGES_DIR/aur.txt" | sort -u)

# Every package the release manifest names is served by the channel. Those
# that are also Arch roots stay roots — resolving Arch's cage is how cage's
# own dependencies reach the closure — and get their marker below. The rest
# have no Arch package to resolve at all.
declare -A channel_set
while IFS=$'\t' read -r name _ _; do
    [[ -n "$name" ]] && channel_set[$name]=1
done < <(manifest_entries "$META_MANIFEST")
(( ${#channel_set[@]} > 0 )) || { echo "ERROR: $META_MANIFEST names no packages." >&2; exit 1; }

# installer.txt is the live-ISO Calamares dep list (kf6-*, qt5-*,
# etc.); those libs only need to exist in the live env so Calamares
# can run, NOT on the installed system. Exclude that file from the
# meta closure so its entries don't bloat shedos-meta. The file still
# feeds the ISO build's package list.
ARCH_ROOTS=()
while IFS= read -r pkg; do
    [[ -z "$pkg" || "$pkg" =~ ^# ]] && continue
    [[ "$pkg" == shedos-* ]] && continue
    [[ -n ${aur_set[$pkg]:-} ]] && continue
    ARCH_ROOTS+=("$pkg")
done < <(
    find "$PACKAGES_DIR/official" -maxdepth 1 -type f -name '*.txt' \
        ! -name 'installer.txt' -print0 \
        | xargs -0 grep -hEv '^\s*(#|$)' \
        | sort -u
)

mapfile -t ARCH_ROOTS < <(printf '%s\n' "${ARCH_ROOTS[@]}" | sort -u)
echo "Arch roots: ${#ARCH_ROOTS[@]} packages"

TMPDIR=$(mktemp -d)
trap "rm -rf $TMPDIR" EXIT
mkdir -p "$TMPDIR/db"

cat > "$TMPDIR/pacman.conf" << 'EOF'
[options]
HoldPkg     = pacman glibc
Architecture = x86_64
SigLevel    = Never
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
EOF

echo "Syncing pacman databases into $TMPDIR/db ..."
pacman -Sy --noconfirm \
    --dbpath "$TMPDIR/db" \
    --config "$TMPDIR/pacman.conf" >/dev/null

echo "Resolving Arch transitive closure ..."
pacman -Sp --noconfirm \
    --dbpath "$TMPDIR/db" \
    --config "$TMPDIR/pacman.conf" \
    --print-format '%n' \
    "${ARCH_ROOTS[@]}" \
    | grep -vE '^shedos-' \
    | grep -vE '^(virtualbox-guest-modules-arch|virtualbox-host-modules-arch)$' \
    | sort -u > "$TMPDIR/closure.txt"

# The marker. A closure name the manifest also names is one Arch and the
# channel both have, and the channel's is the one a ShedOS box installs. Said
# in the file rather than left to repository order, which is what used to
# decide it.
replaced=0
{
    cat << 'EOF'
# AUTO-GENERATED by tools/resolve-meta-closure.sh; do not edit.
# Full transitive closure of packages/official/*.txt resolved against
# core/extra/multilib. Consumed by tools/render-meta-depends.sh to
# populate shedos-meta's depends=() with every Arch transitive dep
# explicit, so install-time pacstrap has no virtual-provider rolls.
# A name followed by a tab and "replaced" is served by the ShedOS
# channel rather than by Arch, and the renderer emits the release
# manifest's pinned form of it.
# Regenerate: sudo tools/resolve-meta-closure.sh

EOF
    while IFS= read -r p; do
        if [[ -n ${channel_set[$p]:-} ]]; then
            printf '%s\treplaced\n' "$p"
            replaced=$((replaced + 1))
        else
            printf '%s\n' "$p"
        fi
    done < "$TMPDIR/closure.txt"
} > "$OUTPUT_FILE"

TOTAL=$(grep -cv '^#\|^$' "$OUTPUT_FILE")
echo ""
echo "Wrote $OUTPUT_FILE ($TOTAL packages, $replaced replaced by the channel)."

if [ -n "${SUDO_USER:-}" ]; then
    chown "$SUDO_USER:$(id -gn "$SUDO_USER")" "$OUTPUT_FILE"
    echo "Restored ownership to user: $SUDO_USER"
fi

# Cross-check that every virtual provide in the closure has its
# alternative providers covered by packages/meta-conflicts.txt. Without
# this, pacstrap's noninteractive default (alphabetical first) silently
# picks a provider that conflicts with an explicit dep (e.g. jack2 over
# pipewire-jack) and aborts the transaction with an unresolvable conflict.
echo ""
echo "Cross-checking virtual-provider disambiguation..."

declare -A in_conflicts=()
while IFS= read -r entry; do
    [[ -n "$entry" ]] && in_conflicts[$entry]=1
done < <(list_names "$META_CONFLICTS")
(( ${#in_conflicts[@]} > 0 )) \
    || { echo "ERROR: $META_CONFLICTS names nothing." >&2; exit 1; }

declare -A in_closure=()
while IFS= read -r p; do
    [[ -n "$p" ]] && in_closure[$p]=1
done < "$TMPDIR/closure.txt"

# For every closure package, collect its `provides=` virtuals via
# pacman -Si and find sibling providers. We only flag when (a) the
# virtual has multiple concrete providers in available repos AND (b)
# none of the alternative providers are already in the conflicts list.
violations=0
checked_virtuals=0
declare -A reported=()

while IFS= read -r line; do
    [[ -n "$line" ]] || continue
    case "$line" in
        "Provides "*)
            virtuals=${line#Provides }
            virtuals=${virtuals#: }
            [[ "$virtuals" == "None" ]] && continue
            for v in $virtuals; do
                # Strip versioned-provides suffix (libfoo.so=12-64 → libfoo.so).
                vname=${v%%=*}
                vname=${vname%%>=*}
                vname=${vname%%<=*}
                [[ -z "$vname" ]] && continue
                [[ -n ${reported[$vname]:-} ]] && continue
                reported[$vname]=1
                checked_virtuals=$((checked_virtuals + 1))

                # Find every concrete provider of this virtual reachable
                # from core/extra/multilib. -Ssq doesn't expand provides;
                # -Sp on the bare name does.
                mapfile -t providers < <(
                    pacman -Sp --noconfirm --print-format '%n' \
                        --dbpath "$TMPDIR/db" \
                        --config "$TMPDIR/pacman.conf" \
                        "$vname" 2>/dev/null | sort -u
                )
                (( ${#providers[@]} <= 1 )) && continue

                in_closure_count=0
                missing_conflicts=()
                for p in "${providers[@]}"; do
                    if [[ -n ${in_closure[$p]:-} ]]; then
                        in_closure_count=$((in_closure_count + 1))
                    elif [[ -z ${in_conflicts[$p]:-} ]]; then
                        missing_conflicts+=("$p")
                    fi
                done

                # If exactly one provider is in the closure (the one we
                # picked) but other providers exist that are NOT listed
                # in the conflicts file, the renderer needs to add them.
                if (( in_closure_count == 1 )) && (( ${#missing_conflicts[@]} > 0 )); then
                    echo "  WARN virtual '$vname': closure has 1 of ${#providers[@]} providers; missing from meta-conflicts.txt: ${missing_conflicts[*]}"
                    violations=$((violations + 1))
                fi
            done
            ;;
    esac
done < <(
    pacman -Si --dbpath "$TMPDIR/db" --config "$TMPDIR/pacman.conf" \
        $(grep -v '^#' "$TMPDIR/closure.txt" | tr '\n' ' ') 2>/dev/null \
        | awk '/^Provides /'
)

echo "  checked $checked_virtuals distinct virtuals; $violations need meta-conflicts.txt updates"
if (( violations > 0 )); then
    echo ""
    echo "ERROR: packages/meta-conflicts.txt is out of sync with"
    echo "       upstream's virtual-provider landscape. Add the packages"
    echo "       listed above to it, then re-run this script to verify."
    exit 1
fi

echo "=========================================="
