#!/bin/bash
# resolve-meta-closure.sh — write packages/.meta-closure.txt as the
# fully-resolved Arch transitive closure of shedos-meta's depends.
#
# Without this, render-meta-depends.sh names only the broad-list
# roots; install-time pacstrap then picks alphabetical defaults for
# any unpinned virtual provider — same trap that broke the live-ISO
# build (jack → jack2, pipewire-session-manager → pipewire-media-session).
#
# Closure input: packages/official/*.txt (broad Arch + multilib roots).
# AUR + shedos-* names are filtered from the resolution input — they
# aren't in pacman repos at script-run time — and re-applied verbatim
# by render-meta-depends.sh. Any AUR-introduced transitive Arch dep
# that isn't already in the broad closure gets pulled in by pacman at
# install time; that's a small remaining surface but keeps the script
# robust against stale files in archiso/shedos-repo/.
#
# Requires root for `pacman -Sy` (db sync). Runs in an isolated
# tempdir so the host /var/lib/pacman is untouched. Locally:
# `sudo scripts/resolve-meta-closure.sh`.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
PACKAGES_DIR="$PROJECT_ROOT/packages"
OUTPUT_FILE="$PACKAGES_DIR/.meta-closure.txt"

if [[ $EUID -ne 0 ]]; then
    echo "ERROR: must be run as root — pacman -Sy syncs the db." >&2
    echo "       Run: sudo $0" >&2
    exit 1
fi

echo "=========================================="
echo "Resolving shedos-meta Arch closure"
echo "=========================================="

declare -A aur_set
while IFS= read -r p; do
    [[ -n "$p" ]] && aur_set[$p]=1
done < <(grep -hEv '^\s*(#|$)' "$PACKAGES_DIR/aur.txt" 2>/dev/null | sort -u)

# installer.txt is the live-ISO Calamares dep list (kf6-*, qt5-*,
# etc.) — those libs only need to exist in the live env so Calamares
# can run, NOT on the installed system. Exclude that file from the
# meta closure so its entries don't bloat shedos-meta. The file still
# feeds archiso/packages.x86_64 via generate-package-list.sh.
ARCH_ROOTS=()
while IFS= read -r pkg; do
    [[ -z "$pkg" || "$pkg" =~ ^# ]] && continue
    [[ "$pkg" == shedos-* ]] && continue
    [[ -n ${aur_set[$pkg]:-} ]] && continue
    ARCH_ROOTS+=("$pkg")
done < <(
    find "$PACKAGES_DIR/official" -maxdepth 1 -type f -name '*.txt' \
        ! -name 'installer.txt' -print0 \
        | xargs -0 grep -hEv '^\s*(#|$)' \
        | sort -u
)

mapfile -t ARCH_ROOTS < <(printf '%s\n' "${ARCH_ROOTS[@]}" | sort -u)
echo "Arch roots: ${#ARCH_ROOTS[@]} packages"

TMPDIR=$(mktemp -d)
trap "rm -rf $TMPDIR" EXIT
mkdir -p "$TMPDIR/db"

cat > "$TMPDIR/pacman.conf" << 'EOF'
[options]
HoldPkg     = pacman glibc
Architecture = x86_64
SigLevel    = Never
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
EOF

echo "Syncing pacman databases into $TMPDIR/db ..."
pacman -Sy --noconfirm \
    --dbpath "$TMPDIR/db" \
    --config "$TMPDIR/pacman.conf" >/dev/null

echo "Resolving Arch transitive closure ..."
pacman -Sp --noconfirm \
    --dbpath "$TMPDIR/db" \
    --config "$TMPDIR/pacman.conf" \
    --print-format '%n' \
    "${ARCH_ROOTS[@]}" \
    | grep -vE '^shedos-' \
    | grep -vE '^(linux|linux-headers|virtualbox-guest-modules-arch|virtualbox-host-modules-arch)$' \
    | sort -u > "$TMPDIR/closure.txt"

{
    cat << 'EOF'
# AUTO-GENERATED by scripts/resolve-meta-closure.sh — do not edit.
# Full transitive closure of packages/official/*.txt resolved against
# core/extra/multilib. Consumed by scripts/render-meta-depends.sh to
# populate shedos-meta's depends=() with every Arch transitive dep
# explicit, so install-time pacstrap has no virtual-provider rolls.
# Regenerate: sudo scripts/resolve-meta-closure.sh

EOF
    cat "$TMPDIR/closure.txt"
} > "$OUTPUT_FILE"

TOTAL=$(grep -cv '^#\|^$' "$OUTPUT_FILE")
echo ""
echo "Wrote $OUTPUT_FILE ($TOTAL packages)."

if [ -n "${SUDO_USER:-}" ]; then
    chown "$SUDO_USER:$(id -gn "$SUDO_USER")" "$OUTPUT_FILE"
    echo "Restored ownership to user: $SUDO_USER"
fi

# Cross-check that every virtual provide in the closure has its
# alternative providers covered by render-meta-depends.sh's
# shedos_conflicts=(). Without this, pacstrap's noninteractive default
# (alphabetical first) silently picks a provider that conflicts with
# an explicit dep — e.g. jack2 over pipewire-jack — and aborts the
# transaction with an unresolvable conflict.
echo ""
echo "Cross-checking virtual-provider disambiguation..."

renderer="$SCRIPT_DIR/render-meta-depends.sh"
declare -A in_conflicts=()
if [[ -f "$renderer" ]]; then
    # Parse shedos_conflicts=( … ) array. Tolerates comments and one entry
    # per line; matches the layout the renderer ships.
    while IFS= read -r entry; do
        in_conflicts[$entry]=1
    done < <(
        awk '
            /^shedos_conflicts=\(/ { seen=1; next }
            seen && /^\)/          { exit }
            seen {
                sub(/#.*/, "")
                for (i=1;i<=NF;i++) {
                    gsub(/[()'"'"'"]/, "", $i)
                    if ($i != "") print $i
                }
            }
        ' "$renderer"
    )
fi

declare -A in_closure=()
while IFS= read -r p; do
    [[ -n "$p" ]] && in_closure[$p]=1
done < "$TMPDIR/closure.txt"

# For every closure package, collect its `provides=` virtuals via
# pacman -Si and find sibling providers. We only flag when (a) the
# virtual has multiple concrete providers in available repos AND (b)
# none of the alternative providers are already in shedos_conflicts.
violations=0
checked_virtuals=0
declare -A reported=()

while IFS= read -r line; do
    [[ -n "$line" ]] || continue
    case "$line" in
        "Provides "*)
            virtuals=${line#Provides }
            virtuals=${virtuals#: }
            [[ "$virtuals" == "None" ]] && continue
            for v in $virtuals; do
                # Strip versioned-provides suffix (libfoo.so=12-64 → libfoo.so).
                vname=${v%%=*}
                vname=${vname%%>=*}
                vname=${vname%%<=*}
                [[ -z "$vname" ]] && continue
                [[ -n ${reported[$vname]:-} ]] && continue
                reported[$vname]=1
                checked_virtuals=$((checked_virtuals + 1))

                # Find every concrete provider of this virtual reachable
                # from core/extra/multilib. -Ssq doesn't expand provides;
                # -Sp on the bare name does.
                mapfile -t providers < <(
                    pacman -Sp --noconfirm --print-format '%n' \
                        --dbpath "$TMPDIR/db" \
                        --config "$TMPDIR/pacman.conf" \
                        "$vname" 2>/dev/null | sort -u
                )
                (( ${#providers[@]} <= 1 )) && continue

                in_closure_count=0
                missing_conflicts=()
                for p in "${providers[@]}"; do
                    if [[ -n ${in_closure[$p]:-} ]]; then
                        in_closure_count=$((in_closure_count + 1))
                    elif [[ -z ${in_conflicts[$p]:-} ]]; then
                        missing_conflicts+=("$p")
                    fi
                done

                # If exactly one provider is in the closure (the one we
                # picked) but other providers exist that are NOT listed
                # in shedos_conflicts, the renderer needs to add them.
                if (( in_closure_count == 1 )) && (( ${#missing_conflicts[@]} > 0 )); then
                    echo "  WARN virtual '$vname': closure has 1 of ${#providers[@]} providers; missing from shedos_conflicts: ${missing_conflicts[*]}"
                    violations=$((violations + 1))
                fi
            done
            ;;
    esac
done < <(
    pacman -Si --dbpath "$TMPDIR/db" --config "$TMPDIR/pacman.conf" \
        $(grep -v '^#' "$TMPDIR/closure.txt" | tr '\n' ' ') 2>/dev/null \
        | awk '/^Provides /'
)

echo "  checked $checked_virtuals distinct virtuals; $violations need shedos_conflicts updates"
if (( violations > 0 )); then
    echo ""
    echo "ERROR: shedos_conflicts in render-meta-depends.sh is out of sync"
    echo "       with upstream's virtual-provider landscape. Add the"
    echo "       packages listed above to the shedos_conflicts=() array,"
    echo "       then re-run this script to verify."
    exit 1
fi

echo "=========================================="
